<?php
namespace App\Utilities;

use Illuminate\Support\Arr;

class Helper
{
    /**
     *    Add product to clickbank
     *    @param array $data
     *
     */

    public function addProduct($data)
    {
        $arr         = Arr::except($data, 'sku');
        $queryString = http_build_query($arr);

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://api.clickbank.com/rest/1.3/products/{$data['sku']}?" . $queryString);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');

        $headers   = array();
        $headers[] = 'Authorization: DEV-6JV3FQGROH27F223599A0D37BHEJJ829:API-T4C75Q6ELOT4B9ANNHCC573J2IDQQDI3';
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        curl_close($ch);
        return $result;

    }
    /**
     *   Get All Orders from Clickbank
     *
     *
     */
    public function allOrders()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.clickbank.com/rest/1.3/orders2/list');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        $headers   = array();
        $headers[] = 'Authorization: DEV-6JV3FQGROH27F223599A0D37BHEJJ829:API-T4C75Q6ELOT4B9ANNHCC573J2IDQQDI3';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        return $result;

    }

}
